# Generated by Django 5.1.3 on 2024-11-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Обычный Пользователь'), (2, 'Менеджер'), (3, 'Бухгалтер')], default=1),
        ),
    ]
